url: https://uypanha.github.io
baseurl: ""
reumeUrl: "https://uypanha.github.io/files/Resume-PanhaUy.pdf"

# Site settings
title: Panha UY, Mr
logo: img/site/logo.png
favicon: img/site/favicon.png
position: Senior Mobile<br>Engineer
email: uypanha.dev@gmail.com
phoneno: +(855) 016 225 163
description: "For more than a decade, Iâ€™ve been designing and building mobile applications that users love and businesses rely on. I specialize in clean architecture, high performance, and thoughtfully crafted user experiences that scale seamlessly as products grow."

#

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/panha_uy
  - title: facebook
    url: https://www.facebook.com/uypanha.dev
  - title: instagram
    url: https://www.instagram.com/panha__uy
  - title: linkedin
    url: https://www.linkedin.com/in/uypanha/
  - title: bitbucket 
    url: https://bitbucket.org/steven_phanha/
  - title: github
    url: http://github.com/uypanha

# Postal address (add as many lines as necessary)
address:
  - line: St BT, House No R74, Preylgnor Village, Sangkat Chaom Chau 2
  - line: Khan Pur Senchey, CA 120910

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
